In [24]:
import numpy as np
arr=np.array([10,20,30,40,50,60])
print(arr)
print(arr[arr>50])
print(arr[[1,2]])
print(np.sum(arr))
print(np.mean(arr))
print(np.std(arr))
print(np.max(arr))
print(np.min(arr))
print(arr*3)
print(np.sort(arr))
print(np.hstack(arr))
print(np.split(arr,2))
print(np.where(arr==50))
print(np.power(arr,3))
for i in arr:
    print(i)
for i in np.nditer(arr):
    print(i)
    
print(np.delete(arr,1))      


[10 20 30 40 50 60]
[60]
[20 30]
210
35.0
17.07825127659933
60
10
[ 30  60  90 120 150 180]
[10 20 30 40 50 60]
[10 20 30 40 50 60]
[array([10, 20, 30]), array([40, 50, 60])]
(array([4]),)
[  1000   8000  27000  64000 125000 216000]
10
20
30
40
50
60
10
20
30
40
50
60
[10 30 40 50 60]
