#Array indexing

In [14]:
import numpy as np
student=np.array(["ravi","suraj","ram","ankur"])
print(student[[1,3]])


['suraj' 'ankur']


In [12]:
arr=np.array([12,13,14,15])
print(arr[arr>15])

[]


In [13]:
marks=np.array([30,49,50,60,80])
print(marks[marks>55])

[60 80]


#iteration

In [18]:
marks=np.array([30,49,50,60,80])
for i in marks:
    print(i)

30
49
50
60
80


In [19]:
l=[13,14,15,16]
for i in range(13,17):
    print(i)

13
14
15
16


In [27]:
import numpy as np
s=np.array([[12,13,14,15],[14,25,36,75]])
for row in s:
        print(row)


[12 13 14 15]
[14 25 36 75]


In [29]:
for i in np.nditer(s):
    print(i)

12
13
14
15
14
25
36
75


In [32]:
e=np.array([[40,50,50],[40,60,70],[40,60,80]])
for i in np.nditer(e):
    print(i)

40
50
50
40
60
70
40
60
80


#merging or joining two array

In [37]:
w=np.array([40,30,45])
s=np.array([35,65,70])
c=np.concatenate((w,s))
print(c)


[40 30 45 35 65 70]


In [55]:
w=np.array([40,30,45])
s=np.array([35,65,70])
c=(w+s)
print(c)


[ 75  95 115]


In [ ]:
#to search the element is present

In [43]:
arr1=np.array([12,23,35,30])
e=np.where(arr1==30)
print(e)

(array([3]),)


In [ ]:
#sorting

In [5]:
import numpy as np
arr1=np.array([12,23,30,25])
e=np.sort(arr1==30)
print(e)

[False False False  True]


In [6]:
import numpy as np
arr1=np.array([12,23,30,25])
e=np.sort(arr1)
print(e)

[12 23 25 30]


In [10]:
marks=np.array([45,56,78,90,89])
print(marks[marks>55])

[56 78 90 89]


#mathematical operations

In [33]:
marks=np.array([45,56,78,90,89])
print(np.sum(marks))
print(np.average(marks))
print(np.mean(marks))
print(np.max(marks))
print(np.min(marks))
print(np.square(marks))
print(np.power(marks,3))

358
71.6
71.6
90
45
[2025 3136 6084 8100 7921]
[ 91125 175616 474552 729000 704969]


#arrange

In [17]:
arr=np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [42]:
arr=np.arange(10)
print(arr[::2])        #skip every 2nd element

[0 2 4 6 8]


In [43]:
print(arr[1:7:2])    #from index 1 to 6 and skipping every 2nd element

[1 3 5]


#split

In [23]:
arr=np.arange(10)
print(np.split(arr,2))

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]


In [ ]:
#stacking

In [31]:
a=np.array([12,13,24,25])
b=np.array([13,23,34,56])
c=np.vstack((a,b))
print(c)

[[12 13 24 25]
 [13 23 34 56]]


In [29]:
a=np.array([12,13,24,25])
b=np.array([13,23,34,56])
print(np.vstack((a,b)))

[[12 13 24 25]
 [13 23 34 56]]


In [30]:
a=np.array([12,13,24,25])
b=np.array([13,23,34,56])
print(np.hstack((a,b)))

[12 13 24 25 13 23 34 56]


#broadcasting

In [35]:
arr=np.array([12,23,24,22])
print(arr+5)

[17 28 29 27]


In [40]:
arr1=np.array([[69,79],[68,78]])
print(arr1 +[5,10])

[[74 89]
 [73 88]]
