In [1]:
import numpy as np
arr=np.array([10,20,30])
print(arr)

[10 20 30]


In [3]:
import numpy as np
s=np.array(["marks",20,30])
print(s)

['marks' '20' '30']


In [4]:
import numpy as np 
arr=np.array([[12,14,15],[45,35,25]])
print(arr)

[[12 14 15]
 [45 35 25]]


In [6]:
arr1=np.array([12,14])
arr2=np.array([34,15])
print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)
print(arr1/arr2)

[46 29]
[-22  -1]
[408 210]
[0.35294118 0.93333333]


In [7]:
a=np.array([10,20,30,40])
b=np.array([1,2,3,4])
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[11 22 33 44]
[ 9 18 27 36]
[ 10  40  90 160]
[10. 10. 10. 10.]


In [12]:
a=np.array([12,35,23])
print(np.sum(a))
print(np.average(a))
print(np.max(a))
print(np.min(a))
print(np.mean(a))

70
23.333333333333332
35
12
23.333333333333332


In [17]:
def count(n):
 if n==0:
    return
 print(n)
 count(n-1)
count(5)    
    



5
4
3
2
1


In [21]:
def count(n):
    if n==0:
        return
    print("hello")
    count(n-1)
count(6)


hello
hello
hello
hello
hello
hello


In [ ]:
#Recurssion

In [30]:
def factorial(n):
    if n==1:
        return 1
    else:
        return n*factorial(n-1)
print(factorial(5))

120


In [ ]:
#lambda function

In [1]:
def square(e):
    return e*e
print(square(6))    
    

36


In [2]:
square=lambda x:x*x
print(square(5))

25


In [3]:
mul=lambda a,b:a*b
print(mul(2,5))

10


In [6]:
check=lambda num:"even" if num%2==0 else "odd"
print(check(4))

even


In [7]:
check=lambda num:"even" if num%2==0 else "odd"
print(check(7))

odd


In [8]:
def mul(a,b):
    return a*b
print(mul(2,3))    

6


In [ ]:
#sorting

In [9]:
students=[("Ram",80),("Ravi",90),("Mahesh",35)]
result=sorted(students,key=lambda x:x[1])
print(result)

[('Mahesh', 35), ('Ram', 80), ('Ravi', 90)]


In [ ]:
#mapping method

In [10]:
numbers=[1,2,3,4,5]
result=list(map(lambda E:E*E,numbers))
print(result)

[1, 4, 9, 16, 25]


In [ ]:
#filter

In [11]:
num=[13,12,14,15]
result=list(filter(lambda M:M%2==0,num))
print(result)

[12, 14]


In [12]:
num=[13,12,14,15]
result=list(filter(lambda M:M%2!=0,num))
print(result)

[13, 15]


In [19]:
from functools import reduce
num=[13,12,14,15]
result=reduce(lambda X,Y:X+Y,num)
print(result)

54
